### ISSUE TITLE
Anything similar to this to connect to Retroarch instance installed on an Android Tablet?

### ISSUE THREAD

**Issue by Mayorc1978** [jehervy/node-virtual-gamepads#104]
As per title a virtual gamepad to use a smartphone as a virtual gamepad to connect to a Retroarch instance installed on a Tablet.

**Comment by robsdedude** [comment]
> Retroarch instance installed on a Tablet

I'm guessing Android, not iOS? Maybe if you root that tablet you could get this to work as Android is Linux based after all. But I've never tried to achieve anything like it. It might be simpler (not cheaper though), to just by a bluetooth controller and pair it with the tablet. Either way, this issue tracker is probably not a good place to find people that can point you to similar software.
