### ISSUE TITLE
Running as normal user

### ISSUE THREAD

**Issue by Tajnymag** [jehervy/node-virtual-gamepads#57]
Is it really necessary to use port 80 by default? As I see it, the app should start with some unprivileged port and leave the config option only for advanced users.

Running anything as root should be the last resort.

**Comment by robsdedude** [comment]
I'd suggest to keep it this way as 80 is the default http port. What might be an option is to extend the README to explain users how to start the app as unprivileged user.

**Comment by robsdedude** [comment]
There is a little more to it than changing the port number. The app works by writing the input events to `/dev/uniput` which by default is `rw` for `root:root` only [1].

Currently the port can be changed by either setting the new port in `config.json` or set the ENV var `PORT`. The latter feature is currently undocumented :cold_sweat:…

[1] https://stackoverflow.com/questions/11939255/writing-to-dev-uinput-on-ubuntu-12-04

**Comment by robsdedude** [comment]
I'll close this issue as I don't see anything that should be changed regarding this issue.
