### ISSUE TITLE
Feature request: Allow more than four gamepads

### ISSUE THREAD

**Issue by jpziegler** [jehervy/node-virtual-gamepads#61]
Some games allow more than four players. It would be great if we could configure the server to allow arbitrary numbers of controllers.

Right now, this can be achieved to some extent by running multiple servers. (I had to edit a few strings to make it easy to tell controllers apart by name.) But a single server would be ideal.

**Comment by robsdedude** [comment]
I like the idea. One would have to come up with a way to extend the indicator LEDs so that more than 4 players know their player number. Would be happy about a pull request.

**Comment by robsdedude** [comment]
Any designs ideas @jpziegler?

**Comment by jpziegler** [comment]
I was thinking it might work fine to add another row of LEDs under the existing ones. I haven't looked closely at the code to see how hard this would be. Alternatively, we could eliminate the LEDs entirely and just show something like a box with a number in it. Maybe make it look like a cool digital display.

Regarding pull requests: I'd love to chip in, but my time is limited so it might take me a while.

**Comment by sbuller** [comment]
It's worthwhile to keep the familiar mapping for players 1-4, but for additional users the LEDs can be used in combination. Below I've provided two options. 'Simple' provides a straight-forward addition, but 'Extended' maps to binary nicely with a minimum of exceptions.

```
LEDS  | Basic | Simple | Extended
0000  |   --- unpaired ---
0001  |  4
0010  |  3
0011  |                   8
0100  |  2
0101  |                   5
0110  |                   6
0111  |                   7
1000  |  1
1001  |          5        9
1010  |          6       10
1011  |          7       11
1100  |          8       12
1101  |          9       13
1110  |         10       14
1111  |         11       15
```

**Comment by sbuller** [comment]
I knew I'd seen the like before, so I looked up the PS3 documentation.

https://www.playstation.com/manual/pdf/CECH-2001A_2001B-2.85_2.pdf#page=22

The PS3 uses  a different mapping, providing for up to 7 players using up to 2 LEDs.
1001 -> 5
0101 -> 6
0011 -> 7

**Comment by robsdedude** [comment]
Let me quote the manual

> The controller number is shown by the number above the port indicators. For numbers 5-7,
add the numbers of the lit indicators

I like this idea. It's probably the most intuitive for most people. It would also be easy to extend this concept to 8 controllers, which I would aim for. Also, when implementing this I'd like to add some info about this in the README as well. Overall, this should be an easy thing to implement. Not sure when I'll find time to do so, though. Feel free to open a PR.
