### ISSUE TITLE
Create /dev/input/by-path entry

### ISSUE THREAD

**Issue by xarvh** [jehervy/node-virtual-gamepads#63]
When a gamepad connects, an entry is created in `/dev/input/jsX`, however Steam games seem to rely on `/dev/input/by-path` (such as `/dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.0-joystick`).

I suppose I could create a symlink manually, but I was wondering if there isn't a cleaner way to do this?

Thanks in advance.

**Comment by robsdedude** [comment]
I couldn't find an easy way to do that just with uinput. I'm unsure if this is even possible. However, you can write udev rules to achieve this. Sadly, I didn't have time to play around with that.
