### ISSUE TITLE
disconnect after a certain period

### ISSUE THREAD

**Issue by mcdull** [jehervy/node-virtual-gamepads#64]
The web connection valid for minutes.  But it will disconnect and I can never reconnect again. 
will the daemon check the existence and restart? thanks.

**Comment by robsdedude** [comment]
To help you I need some more information. Can you please provide the server's output after changing the config `"logLevel": "info"` to `"logLevel": "debug"`.

**Comment by robsdedude** [comment]
I'll close this. Feel free to reopen it if needed.
