### ISSUE TITLE
Game pad connect failed 

### ISSUE THREAD

**Issue by lancewellspring** [jehervy/node-virtual-gamepads#67]
I set the config log to debug and there’s really no good info. The page works on my phone chrome browser (x.x.x.x:8111), but the 1234 lights are flashing red.  Rpi is Jessie, phone is iPhone X, chrome version is 70.0.3538.75.

![image](https://user-images.githubusercontent.com/6957193/49562636-65dfc680-f8ea-11e8-9e6b-917933e37700.jpg)

The exact same thing happened when I tried to connect from my Windows 10 PC Chrome browser.

**Comment by robsdedude** [comment]
I've just published the changes. Could you do me a favor and install the latest dev version? To do so just checkout the branch `develop` (go into the project directory and run `git fetch origin && git checkout develop`). Then run the server again. Could you also test all features quickly? If everything is working for you I'd make new release.

**Comment by lancewellspring** [comment]
Sorry, I’m I’m the middle of renovating my bathroom... hopefully I’ll be able to test this tonight.  Thanks for your help!

**Comment by robsdedude** [comment]
Any news on this?

**Comment by boisvertdany** [comment]
It is working for me:
![image](https://user-images.githubusercontent.com/8672511/51444878-b14c0980-1ccb-11e9-960d-d8d728c3f074.png)

**Comment by robsdedude** [comment]
Nice. So could you fix the permission error and did you test gamepad, keyboard and touchpad briefly?

**Comment by boisvertdany** [comment]
Yes, I was able to fix the permission error with `sudo modprobe uinput`.
But I've got an error when I installed the dependencies with npm (only on develop, v1.3.0 is fine):
![image](https://user-images.githubusercontent.com/8672511/51801992-0f6c7580-2213-11e9-948b-01cde39e074b.png)
I think it is related to : https://github.com/npm/npm/issues/20954

**Comment by robsdedude** [comment]
Right now I'm moving from shrinkwrap to a npm's lock file. This should also fix this error.
