### ISSUE TITLE
Feature request: modify gamepad

### ISSUE THREAD

**Issue by hyamanieu** [jehervy/node-virtual-gamepads#68]
Dear devs,

we are working on a project where this library comes into play. It works really great, we however need some more flexibility and to modify the gamepad, notably reduce the number of buttons, or eventually delete all buttons and add one joystick.

I first thought the application reads the SVG within gamepads.html the same as it does for the keyboard svg (which, in this case, is inserted dynamically), i.e. it fetches the SVG object IDs (e.g. btnX, btnY). But it isn't the case. I can't find the link between the SVG paths and the uinput constants.

The joystick is an other story, as it is coded in virtual_gamepad_client.js, and this time does look for path3212 in the SVG. (edit) After testing it, the variable attached to it is actually unused. Only the `dirCenter0` path.

Some indications would be highly appreciated. If there is something worth a PR, we will do it.

Thank you.

**Comment by robsdedude** [comment]
Hey and thanks for you interest. This project is indeed not very streamlined as the gamepad, the touchpad, and the keyboard were developed by 3 different people…

### Regarding the link of the SVG paths and the uinput:
`public/js/virtual_gamepad_client.js:126`
```javascript
$(".btn").on("touchstart", function() {
    btnId = $(this).data("btn");
    $("#"+btnId).attr("class", "btnSelected");
    socket.emit("padEvent", {type: 0x01, code: $(this).data("code"), value: 1});
    hapticCallback();
});
```

There you can see that the uinput code is encoded in the `data-code` attribute of the svg paths. See e.g. `public/gamepad.html:997`

```html
<path ... id="btnA" class="btn" data-btn="path3253" data-code="0x130" ... />
```

### Regarding the joystick
I'm actually not too familiar with the used library. But indeed `path3212` isn't used currently. I assume it was used to limit the maximum distance the virtual joystick could be moved. Currently this is done using the `stickRadius` parameter. So yes, as you noted only the the elements with the ids `dirCenter` and `dirContainer` are used. So if you want to create a second joystick you would probably have to
 1. create a new center element in the svg
 2. create a new empty div as container for the joystick
 3. call `new VirtualJoystick` accordingly


I hope this helped. If you have further questions don't hesitate to ask.

**Comment by robsdedude** [comment]
As I don't see how this can be integrated into our repo you should probably fork it and adjust the gamepad as you like. It isn't trivial to write a software that can work with arbitrary SVGs that even have different numbers of buttons and joysticks.  
Therefore, I will close this issue as it isn't feasible.

**Comment by hyamanieu** [comment]
> As I don't see how this can be integrated into our repo you should probably fork it and adjust the gamepad as you like. It isn't trivial to write a software that can work with arbitrary SVGs that even have different numbers of buttons and joysticks.
> Therefore, I will close this issue as it isn't feasible.

Of course, we'll take care of it. Thanks for the kick-off!

**Comment by hyamanieu** [comment]
Adding a second joystick is harder than thought. I had to add support to `uinput.ABS_RX` (0x03) and `uinput.ABS_RY` (0x04) in the `setDirection` and in virtual_gamepad.js, but it worked!

The circle animation is missing, it must be added in joystick.js and seems quite complex. Aesthetic can wait. Thanks again.

**Comment by hyamanieu** [comment]
FYI, I pushed my modifications: https://github.com/hyamanieu/node-custom-virtual-gamepads
it's ugly but it works.
