### ISSUE TITLE
Npm install stuck

### ISSUE THREAD

**Issue by remixmabix** [jehervy/node-virtual-gamepads#75]
Hello guys,

I'm stuck at the forever-monitor install dependancie (armv7, raspberry pi)

Here is the log :

> root@retropie:/home/node-virtual-gamepads` # npm install --verbose

	npm info it worked if it ends with ok
	npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose' ]
	npm info using npm@6.13.4
	npm info using node@v12.16.1
	npm verb npm-session b7b2693e746674c2
	npm info lifecycle virtual-gamepads@1.4.0~preinstall: virtual-gamepads@1.4.0
	npm timing stage:loadCurrentTree Completed in 52ms
	npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
	npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1977ms
	npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2591ms
	npm timing stage:loadIdealTree Completed in 5405ms
	npm timing stage:generateActionsToTake Completed in 1167ms
	npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
	npm verb lock using /root/.npm/_locks/staging-e1f066a1cb997820.lock for /home/node-virtual-gamepads/node_modules/.staging
	npm timing audit submit Completed in 2615ms
	npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 2616ms
	npm timing audit body Completed in 6ms
	[            ......] \ extract:fsevents: sill extract lodash@4.17.15 extracted to /home/node-virtual-gamepads/node_modules/.staging/lodash-f7171efd (7794ms)
	[            ......] \ extract:fsevents: sill extract lodash@4.17.15 extracted to /home/node-virtual-gamepads/node_modules/.staging/lodash-f7171efd (7794ms)
	npm timing action:extract Completed in 237241ms
	npm verb unlock done using /root/.npm/_locks/staging-e1f066a1cb997820.lock for /home/node-virtual-gamepads/node_modules/.staging
	npm timing stage:rollbackFailedOptional Completed in 4ms
	npm timing stage:runTopLevelLifecycles Completed in 249475ms
	npm verb stack Error: exited with error code: 128
	npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
	npm verb stack     at ChildProcess.emit (events.js:311:20)
	npm verb stack     at maybeClose (internal/child_process.js:1021:16)
	npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
	npm verb cwd /home/node-virtual-gamepads
	npm verb Linux 4.14.98-v7+
	npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose"
	npm verb node v12.16.1
	npm verb npm  v6.13.4
	npm ERR! Error while executing:
	npm ERR! /usr/bin/git ls-remote -h -t git://github.com/TooTallNate/ref.git
	npm ERR! 
	npm ERR! fatal: read error: Connexion ré-initialisée par le correspondant
	npm ERR! 
	npm ERR! exited with error code: 128
	npm verb exit [ 1, true ]
	npm timing npm Completed in 252653ms

Thanks for the hand.

**Comment by robsdedude** [comment]
The Readme states

> NOTE: This application is only tested with node version 9. 10 and 12 are known to cause trouble because of the dependencies.

Could you pleas try downgrading your node installation and try again. I have the feeling that this issue is actually caused by something else though. Therefore, I'll leave this issue open until I hear back from you.

**Comment by robsdedude** [comment]
Ok. Due to inactivity and the awesome PR #76 by @jamesgrams that makes this project also run on newer versions of node, I'll close this issue. If you still encounter problems feel free to reopen it.
