### ISSUE TITLE
Compatibility with cloud-game streaming?

### ISSUE THREAD

**Issue by poVoq** [jehervy/node-virtual-gamepads#83]
There is this pretty cool open source project that allows one to stream Retroarch games from a cloud server.

Seems like this would be a perfect fit and might already work to some extend.

I made a post here in case there is a chance for collaborating: https://github.com/giongto35/cloud-game/issues/223

**Comment by robsdedude** [comment]
Cool project. But I don't see how this project would go together with theirs. They already have a browser based gamepad implemented. But sure, if they decide to incorporate this project or parts of it, they could contact me for some support.
