### ISSUE TITLE
bluetooth controllers on Android support?

### ISSUE THREAD

**Issue by poVoq** [jehervy/node-virtual-gamepads#84]
Probably not quite the most common use, but there are some nice Bluetooth gamepad adapters that work fine on Android but are a pain to get working on anything other. Any chance they might be made to work as inputs for this?

**Comment by robsdedude** [comment]
Quite a good change actually. This project supports the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API). So if the browser you are using support this API, external controllers should work fine.
