### ISSUE TITLE
ssl / https

### ISSUE THREAD

**Issue by unclehowell** [jehervy/node-virtual-gamepads#89]
What adjustments need to be made for ssl/https ?
I don't see anything in your repo about this.
Or is this webapp just for insecure lans ?
I ended up using ProxyPass in Apache to solve this in the interim.
Basically the user can access a secure url with https/ port 443 (gamepad.example.com or gamepad.pi.local), inside Apache is resolving the subdomain to Proxy Pass port 8089. Not that anyone cares because this repo is so outdated, but food for thought if anyone is interest

**Comment by robsdedude** [comment]
Sorry for the late reaction. Using a well established SSL proxy (e.g. Apache or nginx) as you did, is the usual way to approach this. Relying on some not so well established https sever is a potential security risk. As it stand right now, this project doesn't support secure connections out of the box. Even though this wouldn't be hard to add, it's not planned for the aforementioned reason and given how simple it is to add a reverse proxy.
